platform :ios, '13.0'

target 'WeatherHub' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WeatherHub
  pod 'SwiftGen', '~> 6.0'
  pod 'SwiftLint', '~> 0.43.1'
  pod 'SFSafeSymbols', '~> 2.1.3'

  target 'WeatherHubTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
